### ISSUE TITLE
Rendered HTML does not properly indent child items

### ISSUE THREAD

**Issue by vsch** [babelmark/babelmark.github.io#1]
The rendered HTML fails to indent the child paragraph blocks and indented code block to align with the text indentation of the parent list item. These align with the list item bullet instead. 

The non-standard layout makes it harder to compare expectations.

Markdown:

```markdown
* item 1
    
    this is not code
    
        this is code
 * item 2
    
    this is not code
    
        this is code
```

HTML:

```html
<ul>
  <li>
    <p>
      item 1
    </p>
    <p>
      this is not code
    </p>
<pre>
      <code>this is code</code>
    </pre>
  </li>
  <li>
    <p>
      item 2
    </p>
    <p>
      this is not code
    </p>
<pre>
      <code>this is code</code>
    </pre>
  </li>
</ul>
```

Renders as:

<img width="610" alt="screen shot 2016-07-31 at 9 37 23 pm" src="https://cloud.githubusercontent.com/assets/10299086/17281188/59a7ee18-5768-11e6-8d5b-4fe572bf7a4c.png">

Instead of:

<img width="429" alt="screen shot 2016-07-31 at 9 46 33 pm" src="https://cloud.githubusercontent.com/assets/10299086/17281189/5e61bbd2-5768-11e6-8ae4-a61fd9b5f0a6.png">

Or GitHub's CSS:

<ul>
  <li>
    <p>
      item 1
    </p>
    <p>
      this is not code
    </p>
<pre>
      <code>this is code</code>
    </pre>
  </li>
  <li>
    <p>
      item 2
    </p>
    <p>
      this is not code
    </p>
<pre>
      <code>this is code</code>
    </pre>
  </li>
</ul>

Note the difference in indentation of child paragraphs and indented code.

**Comment by xoofx** [comment]
Indeed, this should be fixed by commit 95cfc01
