### ISSUE TITLE
Side-by-side preview, or tabbed interface

### ISSUE THREAD

**Issue by waldyrious** [babelmark/babelmark.github.io#10]
It's slightly inconvenient to have the preview/rendered version as a block underneath the resulting html code. In fact, it's even a bit misleading, as I didn't realize it was there until I scrolled down.

Would it be possible / desirable to have either a three-column view (list of implementations; html code; rendered rich text) or a tab interface to swap between the code and the rendered versions (similar to Babelmark 2)?

**Comment by xoofx** [comment]
> It's slightly inconvenient to have the preview/rendered version as a block underneath the resulting html code. In fact, it's even a bit misleading, as I didn't realize it was there until I scrolled down.

For me, that was actually convenient. One of the thing I didn't like in babelmark2. 😉  I don't mind if you want to add an option for having tab view/side-by-side, PR welcome.

**Comment by vassudanagunta** [comment]
Reopen since #12 was reverted?
