### ISSUE TITLE
inline code spans should line wrap on whitespace breaks.

### ISSUE THREAD

**Issue by vassudanagunta** [babelmark/babelmark.github.io#16]
babelmark3 applies `white-space: nowrap` to both code blocks and inline code spans. The latter is very unconventional if not misleading. The default styles for [HTML4 (W3C spec)][2], [HTML5 (W3C spec)][3], [Gecko / Firefox][4], [Webkit / Safari][6] and [Blink / Chrome][8] do not set the `white-space` property for `code` (so it should wrap on white space like other elements). They only set `white-space: pre` on `pre` elements, which is used for block code rendering, not inline code spans.

If you concur, I am happy to submit a PR.

For example, the following Markdown
```
`This very long inline code span should wrap to
new lines when it overflows its container. It
should not be styled the same as code blocks.`
```

renders on babelmark3 as:

<img height="350" alt="Screen Shot 2023-01-14 at 2 31 48 AM" src="https://user-images.githubusercontent.com/2830093/212461612-4c0217bc-2cd1-4bbe-92c3-943c48ea6402.png">

Compare to CommonMark demo:

<img height="200" alt="Screen Shot 2023-01-14 at 2 31 01 AM" src="https://user-images.githubusercontent.com/2830093/212461656-e63e727e-117a-44c7-bb9e-5672d2117549.png">

and to GitHub.com:

<img height="400" alt="Screen Shot 2023-01-14 at 2 34 15 AM" src="https://user-images.githubusercontent.com/2830093/212461683-eaa0ecbc-7b4e-4733-b013-f7dbe179f817.png">

  [2]: http://www.w3.org/TR/CSS2/sample.html
  [3]: http://www.w3.org/TR/html5/rendering.html
  [4]: https://dxr.mozilla.org/mozilla-central/source/layout/style/res/html.css
  [6]: http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css
  [8]: https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/core/css/html.css

**Comment by xoofx** [comment]
Yep, sure, feel free to submit a small PR, thanks!
