### ISSUE TITLE
An unexpected error occured when trying to contact babelmark-proxy

### ISSUE THREAD

**Issue by RogueScholar** [babelmark/babelmark.github.io#19]
I've enjoyed testing various ideas regarding the structure of Markdown documents and their potential robustness across implementations on your site for several years now. So it came as a crushing blow to once again visit it today and be met with the following error message on any attempt to use it:

> An unexpected error occured when trying to contact babelmark-proxy. Reason: timeout, Error status: 0

I hope it's nothing serious and would much appreciate a ping here if/when you restore it to functionality.

**Comment by xoofx** [comment]
Thanks, I just tried it and it seems to work fine with this https://babelmark.github.io/?text=test
Probably just a hiccup?

**Comment by xoofx** [comment]
Oh, you mean maybe for MD4C?

<img width="740" alt="image" src="https://github.com/user-attachments/assets/3b40ac17-638d-4ba0-a022-ca93cd837df3">

**Comment by xoofx** [comment]
I have removed the different markdown engines that were no longer working. I have been trying babelmark a few times today and it's working fine.
