### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Crissov** [babelmark/babelmark.github.io#4]
For a few days now, the service has become really slow and *always* times out after a while, then also deleting all results that already had been received and processed. It does not seem to matter how complex the code is.

**Comment by xoofx** [comment]
Thanks, indeed there is a problem on the server. Trying to figure out how to solve this...

**Comment by xoofx** [comment]
Should be fixed now. Not sure what happened but I did push a few upgrades on some framework used...
