### ISSUE TITLE
Relationship with Babelmark 2?

### ISSUE THREAD

**Issue by waldyrious** [babelmark/babelmark.github.io#9]
[Babelmark 2](https://johnmacfarlane.net/babelmark2/) has a FAQ entry that explains [how it differs from Babelmark 1](http://johnmacfarlane.net/babelmark2/faq.html#what-was-babelmark-1). Since the version number in this project's name seems to indicate that this repo comes after those two, it would be nice if it was documented somewhere what the differences and relationship between Babelmark 2 and Babelmark 3 are.

(I'd be happy to contribute such documentation if I'm given pointers to the relevant info.)

**Comment by waldyrious** [comment]
I apologize for the noise, @xoofx! But now that we're at it, and out of curiosity, have there been any talks with @jgm regarding a possible merge of both codebases under the @commonmark organization, or is that not possible / desirable?

**Comment by xoofx** [comment]
Yes, I talked to @jgm back in the days. But if I recall, @jgm was not appealed by the look and feel of babelmark3 and there were probably a couple of other issues, so I end up releasing babelmark3
